name: Free RDP + TFLite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 saat

    steps:
      - name: Download Ngrok
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      - name: Start RDP
        run: |
          net user runneradmin Passw0rd!
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Start-Process powershell -ArgumentList ".\ngrok.exe tcp 3389" -NoNewWindow

      - name: Install Python + TFLite
        run: |
          choco install python -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir C:\Masking
          Copy-Item masking.py C:\Masking\masking.py
          Copy-Item model.tflite C:\Masking\model.tflite
          Copy-Item deeplabv3-xception65.tflite C:\Masking\deeplabv3-xception65.tflite

      - name: Show RDP info
        run: |
          Write-Host "=== RDP Bağlantı Bilgileri ==="
          Write-Host "1) https://dashboard.ngrok.com → Status → Tunnels → TCP linkini al"
          Write-Host "2) Kullanıcı: runneradmin"
          Write-Host "3) Şifre: Passw0rd!"
