name: Free RDP + TFLite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 saat

    steps:
      # 1️⃣ Repo'yu çek
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Ngrok indir
      - name: Download Ngrok
        shell: cmd
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip

      # 3️⃣ Ngrok zip’i aç
      - name: Extract Ngrok File
        shell: cmd
        run: 7z x ngrok.zip -y

      # 4️⃣ Token ayarla
      - name: Set Ngrok Auth Token
        shell: cmd
        run: ngrok.exe authtoken 31FVRSyB653MvWTgNNOGfnKynT8_3Mh6nV5aEpdARHGwVZWWB

      # 5️⃣ RDP ayarları
      - name: Start RDP
        shell: cmd
        run: |
          net user runneradmin Passw0rd!
          powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
          powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0"

      # 6️⃣ Ngrok tünel aç
      - name: Open Tunnel
        shell: cmd
        run: start /B ngrok.exe tcp 3389

      # 7️⃣ Python ve TFLite (tensorflow-cpu ile)
      - name: Install Python + TFLite
        shell: cmd
        run: |
          choco install python -y
          python -m pip install --upgrade pip
          pip install tensorflow-cpu
          mkdir C:\Masking
          copy masking.py C:\Masking\masking.py
          copy deeplabv3-xception65.tflite C:\Masking\deeplabv3-xception65.tflite

      # 8️⃣ RDP bilgilerini göster
      - name: Show RDP info
        shell: cmd
        run: |
          echo === RDP Bağlantı Bilgileri ===
          echo 1) https://dashboard.ngrok.com → Status → Tunnels → TCP linkini al
          echo 2) Kullanıcı: runneradmin
          echo 3) Şifre: Passw0rd!
