name: Free RDP + TFLite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 saat

    steps:
      - name: Download Ngrok
        shell: cmd
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip
          7z x ngrok.zip -y

      - name: Set Ngrok Auth Token
        run: |
          .\ngrok.exe authtoken 1pOPLimRuIfv2P7hmyFN55jjkE5_6VBEjx9BqpjWXDbb4iX86


      - name: Start RDP
        run: |
          net user runneradmin Passw0rd!
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
      - name: Open Tunnel.
        run: |   
          Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp 3389" -NoNewWindow

      - name: Install Python + TFLite
        run: |
          choco install python -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir C:\Masking
          Copy-Item masking.py C:\Masking\masking.py
          Copy-Item deeplabv3-xception65.tflite C:\Masking\deeplabv3-xception65.tflite

      - name: Show RDP info
        run: |
          Write-Host "=== RDP Bağlantı Bilgileri ==="
          Write-Host "1) https://dashboard.ngrok.com → Status → Tunnels → TCP linkini al"
          Write-Host "2) Kullanıcı: runneradmin"
          Write-Host "3) Şifre: Passw0rd!"
